<script src="./scripts/plugins/jquery.min.js"></script>
<script src="./scripts/plugins/bootstrap.bundle.min.js"></script>
<script src="./scripts/plugins/aos.js"></script>
<script src="./scripts/plugins/swiper-bundle.min.js"></script>  
<script src="./scripts/plugins/ScrollMagic.min.js"></script>  
<script src="./scripts/plugins/greensock/TweenMax.min.js"></script>  
<script src="https://unpkg.co/gsap@3/dist/gsap.min.js"></script> 
<script src="./scripts/plugins/greensock/animation.gsap.js"></script> 
<script src="https://unpkg.com/gsap@3/dist/ScrollTrigger.min.js "></script> 
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.min.js"></script>
<script src="./scripts/default/ui.js"></script>